<?php

namespace AppBundle\Repository;

/**
 * ReceiptItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiptItemRepository extends \Doctrine\ORM\EntityRepository
{
}
